---
title: "Untitled"
author: "AFC"
date: "2023-05-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


librerias y paquetes
```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
```


datos
```{r}
# Filtramos la base de datos con 10 aerolineas y quito columna ids 

dataf <- read.csv("vuelos_raw.csv")

dataf$Fecha.I <- as.POSIXct(dataf$Fecha.I, format = "%Y-%m-%d")
dataf$Fecha.O <- as.POSIXct(dataf$Fecha.O, format = "%Y-%m-%d")

params <- c(dataf$OPERA == 'Aeromexico' | dataf$OPERA == 'Air Canada' | dataf$OPERA == 'Air France' | dataf$OPERA == 'American Airlines' | dataf$OPERA == 'Avianca' | dataf$OPERA == 'British Airways' | dataf$OPERA == 'Delta Air' | dataf$OPERA == 'Iberia' | dataf$OPERA == 'K.L.M.' | dataf$OPERA == 'United Airlines')

lim_minutos <- 15

vuelos <- subset(dataf, select = -X) %>%
  filter(params) %>%
  mutate(dif_day = as.numeric(difftime(Fecha.O, Fecha.I, units = "days")),
         dif_day = str_replace(dif_day, "days", ""),
         dif_min_HoraO = as.numeric(difftime(as.POSIXct(paste(Sys.Date(), Hora.O)), as.POSIXct(paste(Sys.Date(), "00:00:00")), units = "mins")),
         dif_min_HoraI = as.numeric(difftime(as.POSIXct(paste(Sys.Date(), "24:00:00")), as.POSIXct(paste(Sys.Date(), Hora.I)), units = "mins")),
         suma_dif_min = dif_min_HoraO + dif_min_HoraI) %>%
  mutate(dif_minutos = ifelse(dif_day == "0", dif_min, suma_dif_min),
         dif_minutos = str_replace(dif_minutos, "mins", ""),
         dif_minutos = as.numeric(dif_minutos)) %>%
  mutate(atraso = ifelse(dif_minutos > lim_minutos, 1, 0)) %>%
  mutate(aerolinea = OPERA) %>%
  select(-c(1:8),-dif_min_HoraO, -dif_min_HoraI, -suma_dif_min, -TIPOVUELO,-dif_min,-atraso_15)

```
Base para modelo
```{r}
meses <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
           "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
dia <- c("Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo")
pdia <- c("mañana","tarde","noche")
aerol <- c("Aeromexico","Air Canada","Air France","American Airlines",
           "Avianca","British Airways","Delta Air","Iberia","K.L.M.","United Airlines")

#Tener todas las variables del modelo en numericas iniciando en 1 excepto la var objetivo va de 0 a 1
vuelos_modelo <- vuelos |>
  mutate(temporada_alta = recode(temporada_alta, `1` = 2, `0` = 1))|>
  mutate(MES = recode(MES, !!!setNames(1:12, meses))) |>
  mutate(DIANOM = recode(DIANOM, !!!setNames(1:7, dia))) |>
  mutate(periodo_dia = recode(periodo_dia, !!!setNames(1:3, pdia))) |>
  mutate(aerolinea = recode(aerolinea, !!!setNames(1:10, aerol)))
  
```

1. Analisis de la base de datos

```{r}
vuelos_tbl <- vuelos |> 
  group_by(OPERA) |>
  summarise(num_vuelos=n(),num_atrasos=sum(atraso15min),
            pct_atrasos=round(mean(atraso15min)*100,1),
            min_atrasos=round(mean(dif_minutos),1),
            .groups = 'drop')
```


GrafiCas eda
```{r}
#GRAFICA TOTAL VUELOS
vuelos_tbl$resaltado <- ifelse(vuelos_tbl$OPERA == "Air Canada", "Resaltado", "Normal")
vuelos_tbl <- vuelos_tbl[order(-vuelos_tbl$total_count), ]
# Crear el gráfico de barras con ggplot y geom_bar
ggplot(vuelos_tbl, aes(x = reorder(OPERA, total_count), y = total_count, fill = resaltado)) +
  geom_bar(stat = "identity",color="black") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Aerolínea", y = "# Vuelos") +
  
  # Cambiar los ejes vertical y horizontal
  theme(axis.text.x = element_text(hjust = 0, color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.title.y = element_text(color = "black"), 
        legend.position = "none") +
  
  # Agregar etiquetas con el valor puntual en las barras
  geom_text(aes(label = total_count), color = "white", hjust = 1.5)+
  scale_fill_manual(values = c("Resaltado" = "maroon4", "Normal" = "steelblue"))
```


```{r}
#GRAFICA TOTAL ATRASOS
vuelos_tbl <- vuelos_tbl[order(-vuelos_tbl$atraso), ]
# Crear el gráfico de barras con ggplot y geom_bar
ggplot(vuelos_tbl, aes(x = reorder(OPERA, atraso), y = atraso, fill = resaltado)) +
  geom_bar(stat = "identity", color="black") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Aerolínea", y = "# Retrasos") +
  
  # Cambiar los ejes vertical y horizontal
  theme(axis.text.x = element_text(hjust = 0, color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.title.y = element_text(color = "black"), 
        legend.position = "none") +
  
  # Agregar etiquetas con el valor puntual en las barras
  geom_text(aes(label = atraso), color = "white", hjust = 1.1)+
  scale_fill_manual(values = c("Resaltado" = "maroon4", "Normal" = "steelblue"))
```

```{r}
#GRAFICA % ATRASOS
vuelos_tbl <- vuelos_tbl[order(-vuelos_tbl$atraso_pct), ]
# Crear el gráfico de barras con ggplot y geom_bar
ggplot(vuelos_tbl, aes(x = reorder(OPERA, atraso_pct), y = atraso_pct, fill = resaltado)) +
  geom_bar(stat = "identity",color="black") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Aerolínea", y = "% Vuelos atrasados") +
  
  # Cambiar los ejes vertical y horizontal
  theme(axis.text.x = element_text(hjust = 0, color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.title.y = element_text(color = "black"), 
        legend.position = "none") +
  
  # Agregar etiquetas con el valor puntual en las barras
  geom_text(aes(label = atraso_pct), color = "white", hjust = 1.3)+
  scale_fill_manual(values = c("Resaltado" = "maroon4", "Normal" = "steelblue"))
```

```{r}
#GRAFICA TIEMPO PROMEDIO ATRASOS
vuelos_tbl <- vuelos_tbl[order(-vuelos_tbl$tiempo_prom), ]

# Crear el gráfico de barras con ggplot y geom_bar
ggplot(vuelos_tbl, aes(x = reorder(OPERA, tiempo_prom), y = tiempo_prom, fill = resaltado)) +
  geom_bar(stat = "identity", color="black") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Aerolínea", y = "Tiempo promedio de los atrasos en min.") +
  
  # Cambiar los ejes vertical y horizontal
  theme(axis.text.x = element_text(hjust = 0, color = "black"),
        axis.text.y = element_text(color = "black"),
        axis.title.y = element_text(color = "black"), 
        legend.position = "none") +
  
  # Agregar etiquetas con el valor puntual en las barras
  geom_text(aes(label = tiempo_prom), color = "white", hjust = 1.5)+
  scale_fill_manual(values = c("Resaltado" = "maroon4", "Normal" = "steelblue"))
```

2. Modelo
```{r}
# LIBRERIAS

#install.packages("R2OpenBUGS")
#install.packages("R2jags")
library(R2OpenBUGS)
library(tidyverse)
library(bayesm)
#library(R2jags)
library(coda)

getwd()
setwd('/Users/Beto/Documents/AFC/Finales/Reg_avanzada')

# Semilla para que sea replicable
set.seed(2023)

```

```{r}
# GENERAL

n <- nrow(vuelos_modelo)

#variable objetivo
y <-vuelos_modelo$atraso

#variables categoricas
ds <-vuelos_modelo$DIANOM
ms <-vuelos_modelo$MES
al <-vuelos_modelo$aerolinea
ta <-vuelos_modelo$temporada_alta
pd <-vuelos_modelo$periodo_dia

# MODELO 1

#-Definiendo datos-
data<-list("n"=n,"y"=y,"ds"=ds,"ms"=ms,"al"=al,
           "ta"=ta, "pd"=pd)

#-Definiendo inits-
inits<-function(){list(alpha=0,beta=rep(0,7),gama=rep(0,12),
                       delta=rep(0,10),kappa=rep(0,2),lambda=rep(0,3))}

#-Seleccionando parametros a monitorear-
parameters<-c("alpha.est","beta.est","gama.est","delta.est","kappa.est","lambda.est")

#-Corrida de codigo-
#OpenBUGS
niter <- 1000
cadenas <-2
quema <- 100
adelgaz <-4
deb_gg <- FALSE
modelo.sim<-bugs(data,inits,parameters,model.file="txt_logit.txt",
                n.iter=niter,n.chains=cadenas,n.burnin=quema,n.thin=adelgaz, debug=deb_gg)


```

Analisis modelo1
```{r}
#Traza de la cadena
simula<-as.mcmc.list(modelo.sim)
traceplot(simula)

out<-modelo.sim$sims.list
out.a<-modelo.sim$sims.array


z1<-out.a[,1,1]
z2<-out.a[,2,1]
par(mfrow=c(3,2))
plot(z1,type="l",col="grey50")
lines(z2,col="firebrick2")
y1<-cumsum(z1)/(1:length(z1))
y2<-cumsum(z2)/(1:length(z2))
ymin<-min(y1,y2)
ymax<-max(y1,y2)
plot(y1,type="l",col="grey50",ylim=c(ymin,ymax))
lines(y2,col="firebrick2",ylim=c(ymin,ymax))
hist(z1,freq=FALSE,col="grey50")
hist(z2,freq=FALSE,col="firebrick2")
acf(z1)
acf(z2)


#Resumen (estimadores)
#OpenBUGS
out.sum<-modelo.sim$summary
head(out.sum[,c(1,2,3,4,5,6,7,8,9)])
write.csv((out.sum[,c(1,2,3,4,5,6,7,8,9)]),file="pestim.csv")
par(mfrow=c(1,1))

out.dic<-modelo.sim$DIC
```

